### ISSUE TITLE
Plugin Doesn't Work

### ISSUE THREAD

**Issue by keanegrech** [NoahvdAa/nStaffChat#1]
When I have the permission, it still does not allow me to execute the /sc command. Also the staff join isn't working as it outputs an error in the console.

![error 1](https://user-images.githubusercontent.com/44116193/83432857-78808080-a439-11ea-84a3-62785f7e8c1b.PNG)

https://pastebin.com/JW60qMcY

Thank you for your patience.

**Comment by keanegrech** [comment]
OK never mind, I have managed to fix the staff chat but the join messages are still not working.

**Comment by NoahvdAa** [comment]
What version of bungeecord are you using?

**Comment by keanegrech** [comment]
Turns out I was using a bungee cord version that was outdated, thanks for the help!

**Comment by NoahvdAa** [comment]
No problem, I'll close this issue. Let me know if you experience any other issues.
